---
  name: test
  trigger: 
    - master
  stages:
  - stage: git
    jobs:
    - job: 'git_clone'
      steps:
      - bash: |
            git clone https://github.com/wakaleo/game-of-life.git
            cd game-of-life
      - task: Maven@3 
        inputs:
          goals: 'clean package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/*.xml' 
      - publish: 'target/*.jar'
        artifact: 'gameoflife war file'          
            
        
            
 