---
  name: test
  trigger: 
    - master
  stages:
  - stage: git
    jobs:
    - job: 'git clone'
      steps:
      - bash: |
            git clone https://github.com/wakaleo/game-of-life.git
            cd game-of-life
  - stage: build
    jobs:
    - job: 'Build job'  
      steps:
      - task: Maven@3 
        inputs:
          goals: 'clean package'
  - stage: 'publish test results'
    jobs:
    - job: 'junit results'
      steps:
      - task: Maven@3 
        inputs:
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/*.xml'   
  - stage: 'Archive artifacts'
    jobs:
    - job: Artifacts
      steps:
      - publish: 'target/*.jar'
        artifact: 'gameoflife war file'
